[IV-23-24] Objetivo 9
danieeeld2/LogisticsRoutes pull request #109
Opened 2024-01-04 13:11 UTC by danieeeld2

2024-01-04 19:14 UTC, danieeeld2 commented on internal/suministro.go
> +	direccion				string			`json:"direccion"`
@JJ está casi acabado, pero me he encontrado con el problema de que para que los parámetros sean exportables, deben estar en mayúscula, no sirve solo con la etiqueta, por lo que tendría que ir por todo el código cambiándolo Voy a esperar a que me digas que tal está el resto y si lo otro va bien, pues ya me pongo a cambiar todo esto (*Esto solo afecta a las rutas `PUT` de `camión` y `suministro`, el resto esta testado*)

2024-01-04 19:17 UTC, JJ commented on internal/suministro.go
> +	direccion				string			`json:"direccion"`
¿Por qué necesitas que los parámetros sean exportables?

2024-01-04 19:21 UTC, danieeeld2 commented on internal/suministro.go
> +	direccion				string			`json:"direccion"`
Como trabajamos con `JSON`, al ser una API REST,  yo, en los tests, creo datos de prueba y los transformo a `JSON` con `jsonResponse, err := json.Marshal(camion)`, pero si los parámetros del struct no están en mayúscula, me dice que no son exportables y da error.

2024-01-04 19:24 UTC, JJ requested changes
Aparte de lo comentado, no tengo muy claro qué ruta en concreto activa la lógica de negocio. En los tests no está muy claro, más que nada por la cantidad de tests que hay... Quizás sería mejor agruparlos o hacerlo de forma que se vea explícitamente.

2024-01-04 19:24 UTC, JJ commented on internal/api.go
> +		http.Error(w, "Error al convertir a JSON", http.StatusInternalServerError)
Os comenté que el `InternalServerError` no era nunca algo que pudiera devolver la aplicación, es algo que devuelve lo que esté delante de la aplicación (proxy, CDN) en caso de que esta no funcione. Piensa qué error podría ser el más adecuado en este caso.

2024-01-04 19:24 UTC, JJ commented on internal/api_test.go
> +	if camion.Matricula != matricula {
Igual sería un poco más comprensible que agruparas en subtests.

2024-01-04 19:29 UTC, danieeeld2 commented
> Aparte de lo comentado, no tengo muy claro qué ruta en concreto activa la lógica de negocio. En los tests no está muy claro, más que nada por la cantidad de tests que hay... Quizás sería mejor agruparlos o hacerlo de forma que se vea explícitamente.

En sí no la activa ninguna, porque como en la objetivo anterior me pusiste: "igual sería más conveniente un POST que un PUT (donde se supone que ya la tienes, y que la ha calculado el cliente)", pues creí que no debería usarla explicita mente en los test de la `API`. ¿Debería entonces usarla en el test?

2024-01-04 19:30 UTC, danieeeld2 commented on internal/api_test.go
> +	if camion.Matricula != matricula {
> Igual sería un poco más comprensible que agruparas en subtests.

Okay, lo tendré en cuenta, porque la verdad que hasta yo me estaba liando de tanto código.

2024-01-04 19:35 UTC, JJ commented
> > Aparte de lo comentado, no tengo muy claro qué ruta en concreto activa la lógica de negocio. En los tests no está muy claro, más que nada por la cantidad de tests que hay... Quizás sería mejor agruparlos o hacerlo de forma que se vea explícitamente.
> 
> En sí no la activa ninguna, porque como en la objetivo anterior me pusiste: "igual sería más conveniente un POST que un PUT (donde se supone que ya la tienes, y que la ha calculado el cliente)", pues creí que no debería usarla explicita mente en los test de la `API`. ¿Debería entonces usarla en el test?

(se pone el gorro de ChatGPT)
Perdón, creo que me expresé mal. Un POST activaría la lógica de negocio. Si usas un PUT, sin embargo, se supone que la lógica de negocio está en otro lado. Por eso te decía que era más conveniente un POST para activar la lógica de negocio.

2024-01-04 19:39 UTC, danieeeld2 commented
> > > Aparte de lo comentado, no tengo muy claro qué ruta en concreto activa la lógica de negocio. En los tests no está muy claro, más que nada por la cantidad de tests que hay... Quizás sería mejor agruparlos o hacerlo de forma que se vea explícitamente.
> > 
> > 
> > En sí no la activa ninguna, porque como en la objetivo anterior me pusiste: "igual sería más conveniente un POST que un PUT (donde se supone que ya la tienes, y que la ha calculado el cliente)", pues creí que no debería usarla explicita mente en los test de la `API`. ¿Debería entonces usarla en el test?
> 
> (se pone el gorro de ChatGPT) Perdón, creo que me expresé mal. Un POST activaría la lógica de negocio. Si usas un PUT, sin embargo, se supone que la lógica de negocio está en otro lado. Por eso te decía que era más conveniente un POST para activar la lógica de negocio.

😂 buena referencia actual. Okay, lo tendré en cuenta. Voy a ver si entre mañana y pasado lo puedo arreglar, que son los dos últimos días que tengo para dedicarle a la asignatura, por desgracia.

2024-01-04 19:43 UTC, JJ commented
Ánimo.

2024-01-05 13:20 UTC, danieeeld2 commented on internal/api_test.go
> +	if camion.Matricula != matricula {
Resuelto en commit 4f4f1bf2e318117bd5697636905186c6c7116fb6

2024-01-05 13:25 UTC, danieeeld2 commented on internal/api.go
> +		http.Error(w, "Error al convertir a JSON", http.StatusInternalServerError)
Resuelto en commit 228c6d5a6dfd4308bfe46fa69d54de972c2368d9

2024-01-05 13:26 UTC, danieeeld2 commented
> Aparte de lo comentado, no tengo muy claro qué ruta en concreto activa la lógica de negocio. En los tests no está muy claro, más que nada por la cantidad de tests que hay... Quizás sería mejor agruparlos o hacerlo de forma que se vea explícitamente.

Ahora si aplica la lógica de negocio, commit 59da510f0df9feeb9e9552d4a87171239d12d305

2024-01-05 13:29 UTC, danieeeld2 commented
@JJ he solventado un poco lo más indicativo de la revisión de ayer. Hoy no creo que tenga más tiempo, pero mañana a ver si le puedo sacar un ratillo, por si sigue habiendo errores (que seguramente los haya)

2024-01-05 14:00 UTC, JJ approved these changes
:1st_place_medal: Esencialmente es correcto, aunque podría venirle bien un poco de DRY, evitar DELETEs unnecesarios que no tengan nada que ver con las HUs ni con la lógica de negocio, y agrupar los tests según historias de usuario y no funcionalidades (lo que haría un poco más sencillo su evaluación). Enhorabuena.

2024-01-05 14:02 UTC, danieeeld2 commented
> :1st_place_medal: Esencialmente es correcto, aunque podría venirle bien un poco de DRY, evitar DELETEs unnecesarios que no tengan nada que ver con las HUs ni con la lógica de negocio, y agrupar los tests según historias de usuario y no funcionalidades (lo que haría un poco más sencillo su evaluación). Enhorabuena.

Parece mentira acabar todos los objetivos😂. Muchas gracias @JJ

2024-01-05 14:07 UTC, danieeeld2 commented
> > > 🥇 Esencialmente es correcto, aunque podría venirle bien un poco de DRY, evitar DELETEs unnecesarios que no tengan nada que ver con las HUs ni con la lógica de negocio, y agrupar los tests según historias de usuario y no funcionalidades (lo que haría un poco más sencillo su evaluación). Enhorabuena.
> > 
> > 
> > Parece mentira acabar todos los objetivos😂. Muchas gracias @JJ
> 
> El tercero de la historia, si no estoy contando mal... Y el primero fue @amerigal, así que...

Yo creo que este año lo acaba más gente. @Morad02 y @javigp2002 seguro que también lo acaban.

2024-01-05 15:16 UTC, merged

2024-01-05 16:44 UTC, JJ commented
> > > > 🥇 Esencialmente es correcto, aunque podría venirle bien un poco de DRY, evitar DELETEs unnecesarios que no tengan nada que ver con las HUs ni con la lógica de negocio, y agrupar los tests según historias de usuario y no funcionalidades (lo que haría un poco más sencillo su evaluación). Enhorabuena.
> > > 
> > > 
> > > Parece mentira acabar todos los objetivos😂. Muchas gracias @JJ
> > 
> > 
> > El tercero de la historia, si no estoy contando mal... Y el primero fue @amerigal, así que...
> 
> Yo creo que este año lo acaba más gente. @Morad02 y @javigp2002 seguro que también lo acaban.

También @carlotiii30 está a punto. Pero *no pressure*, ¿eh? ;-)