[IV 23-24] Objetivo 1
danieeeld2/LogisticsRoutes pull request #6
Opened 2023-09-23 15:55 UTC by danieeeld2

### Sobre los milestones
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

### Sobre las historias de usuario
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-24 08:05 UTC, JJ requested changes
[Aquí](https://github.com/danieeeld2/LogisticsRoutes/pull/1#pullrequestreview-1629231313) te dije que era un problema poco concreto que tendrías que perfilar; desgraciadamente me parece que no estás concretándolo en la dirección correcta. Nada que incluya ni APIs ni mapas ni, en general, datos que no puedas manejar u obtener fácilmente va a poder ser fácilmente abordable en objetivos sucesivos; cálculo de rutas, en concreto, será prácticamente imposible de abordar. Tampoco puedes contar con APIs y demás.
Teniendo en cuenta eso, deberías repriorizar las historias de usuario para poner en primer lugar las que veas más abordables dentro de este problema; también con respecto a eso, y lo que te dije al aprobar el objetivo 0, deberías concretar un poco más el problema para orientarlo en una dirección que sea abordable dentro de esta asignatura.

2023-09-24 08:05 UTC, JJ commented on docs/milestones.md
> +- [ ] [[M0] Diseño de las estructuras de datos en ficheros](https://github.com/danieeeld2/LogisticsRoutes/milestone/1)
El objetivo no es "diseño de las estructuras de datos". Especifica claramente qué es lo que hace válidas a esas estructuras de datos.
Y por favor, dejaros de hacer equilibros semánticos con las palabras "estructuras de datos", "módulos" y "ficheros". Os dije claramente en clase qué tenía que incluir este milestone. Ponedlo aquí con la misma claridad, especificándolo para vuestros problema en particular.

2023-09-24 08:05 UTC, JJ commented on docs/milestones.md
> +  - Una estructura de datos que nos permita obtener el recorrido más eficiente entre el punto de inicio y el punto de entrega (_Modeliza las carreteras_)
Las estructuras de datos no son capaces de hacer estas cosas.

2023-09-24 08:05 UTC, JJ commented on docs/milestones.md
> +  - Una estructura que almacene las especificaciones del vehículo (_dimensión, peso, indicación de que transporta mercancía peligrosa o no_)
Que las especificaciones del vehículo estén en una o en tres estructuras de datos, o no estén, tiene que decidirse a la hora de modelizar. No especifiquéis absolutamente nada más que el resultado.

2023-09-24 16:54 UTC, danieeeld2 commented
@JJ 👍 voy a empezar creo por leer el objetivo 2 para hacerme una mejor idea de hacia donde enfocarlo y me pongo esta semana a trabajar en ello. A ver si para antes de la clase del jueves lo puedo tener replanteado. Gracias por aportar tantos comentarios, los iré teniendo en cuenta a medida que aporto un nuevo planteamiento al objetivo 😁

2023-09-26 18:33 UTC, JJ commented
> @JJ Listo para revisión, lo he intentado enforcar de manera distinta, de forma que el M1 sea mucho más simple (se trata de buscar cuál es el vehículo más óptimo para una mercancía) y el M2 se construya directamente sobre el M1 (hacer un planning de reparto diario, primando el mayor número de entregas posible), pero no estoy seguro de si entre medias podría existir algún otro pmv posible. He dejado también las otras HU y milestones, pero si prefiere los elimino para que quede todo más limpio.

Sinceramente, entre 2 y 3 no me preocupa demasiado; me preocupa que haya un hueco entre 0 y 1

2023-09-27 13:50 UTC, danieeeld2 commented
@JJ Gracias por la aportación 😄. Mañana detallo más los HUs antes de fusionar las ramas e intentaré ayudar a algún compañero revisando sus PRs; que hoy estoy un poco ocupado :monocle_face:.

2023-09-28 14:18 UTC, danieeeld2 commented
@JJ Voy a ponerme con las aclaraciones que me comentaste. ¿Dónde sería conveniente redactarlo?¿Dentro de las historias de usuario en un user journey?

2023-10-04 15:02 UTC, merged