[IV-23-24] Objetivo 6
danieeeld2/LogisticsRoutes pull request #63
Opened 2023-11-29 23:42 UTC by danieeeld2

2023-11-30 09:26 UTC, javigp2002 approved these changes
:+1: La verdad que está bastante conseguido el objetivo a mi parecer. Toda la documentación está bíen realizada y se siguen los criterios establecidos previamente, asimismo, en los distintos PR veo que los has probado... La única posible pega es que pones las versiones 1.20 y 1.21 son LTS según pones en el issue. Si puedes, intenta que la github action y Circle ejecuten distintas versiones, ahora mismo haces:
- V: 1.20, 1.21
- V: 1.20

Todo esto es como recomendación, tengo 0 pegas con tu objetivo. :100:

2023-11-30 09:48 UTC, danieeeld2 commented
> 👍 La verdad que está bastante conseguido el objetivo a mi parecer. Toda la documentación está bíen realizada y se siguen los criterios establecidos previamente, asimismo, en los distintos PR veo que los has probado... La única posible pega es que pones las versiones 1.20 y 1.21 son LTS según pones en el issue. Si puedes, intenta que la github action y Circle ejecuten distintas versiones, ahora mismo haces:
> 
> * V: 1.20, 1.21
> * V: 1.20
> 
> Todo esto es como recomendación, tengo 0 pegas con tu objetivo. 💯

Gracias por la revisión compañero. Voy a añadir a la documentación de CI las versiones a testar y el porqué, además de implementarlo.

2023-11-30 10:08 UTC, danieeeld2 commented
@JJ está listo para revisión. Nuevamente, gracias por la aportación de las versiones @javigp2002 :)

2023-11-30 11:34 UTC, JJ requested changes
:clap:

2023-11-30 11:34 UTC, JJ commented on .github/workflows/test.yml
> +        go-version: ['1.18', '1.19']
Posiblemente sean versiones sin soporte, así que podrías darle una vuelta, pero me gusta que hayas usado la `matrix`

2023-11-30 11:34 UTC, JJ commented on .github/workflows/test.yml
> +          sed -i 's/1.21/${{matrix.go-version}}/g' go.mod
Je, buen uso de `sed`

2023-11-30 15:13 UTC, danieeeld2 commented on .github/workflows/test.yml
> +        go-version: ['1.18', '1.19']
Ahora mismo creo que está solo con soporte la 1.21 y 1.20 (nos pareció ver esta mañana en clase), entonces me dijo Javi que metiese alguna más antigua. Si solo están estas dos soportadas puedo o que ambas integraciones comprueben las dos o que cada una compruebe una, aunque me daría un poco de pena desperdiciar la `matrix` así 😂

2023-12-01 12:15 UTC, danieeeld2 commented on .github/workflows/test.yml
> +        go-version: ['1.18', '1.19']
Resuelto temporalmente en commit 7ea80a04da8b2f22463af00ead773e1cbfd4d552

2023-12-01 12:17 UTC, merged