[IV-23-24] Objetivo 7
danieeeld2/LogisticsRoutes pull request #80
Opened 2023-12-05 11:18 UTC by danieeeld2

* [ ] ¿Se han registrado todos los eventos relevantes en la aplicación, es decir, se
  han añadido comandos para registrarlos en todos ellos?
* [ ] ¿Se han seguido buenas prácticas en el uso de configuración remota?
* [ ] ¿Se han explicado correctamente las decisiones técnicas que se han tomado
  sobre las bibliotecas usadas?
* [ ] ¿Te has asegurado de que el fichero `.env` no se pueda añadir
accidentalente al repositorio?
* [ ] ¿Los logs y la configuración están en un objeto que se *inyecta* en las
clases manejadoras para su uso?
* [ ] ¿*Realmente* se usan los logs en las diferentes clases en eventos
importantes?
* [ ] ¿Se testea el código creado para logs y configuración, igual que
    cualquier otro código?
* [ ] ¿La clase o módulo de configuración lee *siempre* las variables de entorno?

2023-12-11 08:01 UTC, JJ requested changes
En general está bastante completo, pero al ser el primero me gustaría que afinaras unos pequeños detalles.

2023-12-11 08:01 UTC, JJ commented on .gitignore
> +koanf_config.yaml
OK, buena idea.

2023-12-11 11:23 UTC, JJ commented
Mucho ánimo.

2023-12-11 17:18 UTC, danieeeld2 commented on docs/sistema-configuracion.md
> +Son herramientas que permiten almacenar y acceder a diferentes configuraciones de una aplicación de forma organizada y segura. Estas configuraciones pueden incluir valores como la dirección de un ser
Resuelto en commit 430726c

2023-12-11 17:18 UTC, danieeeld2 commented on docs/sistema-configuracion.md
> +Al utilizar bibliotecas de configuración, nos aseguramos de que la configuración esta separada del resto delcódigo, pudiendo modificarse fácilmente, sin necesidad de cambiar todo el código.
Resuelto en commit 430726c

2023-12-11 17:18 UTC, danieeeld2 commented on docs/sistema-configuracion.md
> +### [Viper](https://pkg.go.dev/github.com/dvln/viper#section-readme)
Resuelto en commit 430726c

2023-12-11 17:28 UTC, danieeeld2 commented on docs/sistema-configuracion.md
> +Trás probar las opciones comentadas, me he encontrado con que **Viper** no consigo instalarlo correctamente en mi proyecto, por una incompatibilidad de las dependencias que no consigo solventar. El r
Resuelto en commit 3d9e615

2023-12-11 17:41 UTC, danieeeld2 commented on docs/sistema-de-logs.md
> +- Prefixo de registro: Permite agregar un prefijo personalizado a los mensajes de registro, lo que es útil para identificar de qué parte de la aplicación provienen los registros.
Resuelto en commit 144fed4

2023-12-11 17:41 UTC, danieeeld2 commented on docs/sistema-de-logs.md
> +- Posibilidad de especificar distintos niveles de impresión: logs, debug, warning, error...
Resuelto en commit 144fed4

2023-12-11 17:41 UTC, danieeeld2 commented on docs/sistema-de-logs.md
> +- Permite asociar clave-valor a los mensajes de log, facilitando en análisis y filtrado de los mismos.
Resuelto en commit 144fed4

2023-12-12 07:17 UTC, JJ approved these changes
:+1:

2023-12-12 07:17 UTC, JJ commented on internal/config.go
> +func loadConfig(confiFile string) (*AppConfig, error) {
Usa `config` y no `confi` de forma consistente, por favor.

2023-12-15 15:28 UTC, danieeeld2 commented on internal/config.go
> +func loadConfig(confiFile string) (*AppConfig, error) {
Resuelto en commit  6bed1dddfc1b2dcc537c743f49b071deb25eb6f1

2023-12-15 15:28 UTC, merged